// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Segfy.Infrastructure.Persistence;

#nullable disable

namespace Segfy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SegfyDbContext))]
    [Migration("20260706010357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Segfy.Domain.Entities.Apolice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RamoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("RamoId");

                    b.ToTable("Apolices", (string)null);
                });

            modelBuilder.Entity("Segfy.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Segfy.Domain.Entities.Ramo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Ramos", (string)null);
                });

            modelBuilder.Entity("Segfy.Domain.Entities.Sinistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApoliceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoNegativa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApoliceId");

                    b.ToTable("Sinistros", (string)null);
                });

            modelBuilder.Entity("Segfy.Domain.Entities.Apolice", b =>
                {
                    b.HasOne("Segfy.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segfy.Domain.Entities.Ramo", null)
                        .WithMany()
                        .HasForeignKey("RamoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Segfy.Domain.Entities.Sinistro", b =>
                {
                    b.HasOne("Segfy.Domain.Entities.Apolice", null)
                        .WithMany()
                        .HasForeignKey("ApoliceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Segfy.Domain.Entities.HistoricoSinistro", "Historico", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DataAlteracao")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("SinistroId")
                                .HasColumnType("uuid");

                            b1.Property<string>("StatusAnterior")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("StatusNovo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("SinistroId");

                            b1.ToTable("HistoricoSinistros", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SinistroId");
                        });

                    b.OwnsOne("Segfy.Domain.ValueObjects.Dinheiro", "ValorAprovado", b1 =>
                        {
                            b1.Property<Guid>("SinistroId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("ValorAprovado");

                            b1.HasKey("SinistroId");

                            b1.ToTable("Sinistros");

                            b1.WithOwner()
                                .HasForeignKey("SinistroId");
                        });

                    b.OwnsOne("Segfy.Domain.ValueObjects.Dinheiro", "ValorEstimado", b1 =>
                        {
                            b1.Property<Guid>("SinistroId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("ValorEstimado");

                            b1.HasKey("SinistroId");

                            b1.ToTable("Sinistros");

                            b1.WithOwner()
                                .HasForeignKey("SinistroId");
                        });

                    b.Navigation("Historico");

                    b.Navigation("ValorAprovado");

                    b.Navigation("ValorEstimado")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
